name: pipeline

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'my testing job 1'
        required: true
        default: 'tetsing-job'

jobs:
  job1:
    name: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: stage1
        run: echo "hello world"
