name: sample work flow

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: my sample workflow
        required: true
        default: 'development'

jobs:
  my-testing-1:
    name: my-testing-job-1
    runs-on: ubuntu-latest

    steps:
      - name: stage 1
        run: echo "Hello-"${{github.event.inputs.name}}
